name: CI/CD Pipeline for ML Model

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
    paths:
      - '**.py'         # Detect changes to Python files
      - '**.dvc'        # Detect changes to DVC files
      - 'data/**'       # Detect changes to data
  pull_request:         # Trigger on pull requests
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Pull data from DVC
    - name: Pull data using DVC
      run: |
        pip install dvc[all]
        dvc pull

    # Step 5: Log in to Google Cloud
    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json

    # Step 6: List files in the GCS bucket using gsutil
    - name: List files in GCS bucket
      run: gsutil ls gs://dvcmlops/data

    # Step 7: Run the ML pipeline
    - name: Run ML pipeline
      run: python pipeline.py

    # Step 8: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 9: Build Docker image
    - name: Build Docker image
      run: docker build -t rbenfraj46/insurance_model:latest .

    # Step 10: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push rbenfraj46/insurance_model:latest
