name: CI/CD Pipeline for ML Model

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
    paths:
      - '**.py'         # Detect changes to Python files
      - 'data/**'       # Detect changes to data
  pull_request:         # Trigger on pull requests
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    # Step 6: Run the ML pipeline
    - name: Run ML pipeline
      run: python pipeline.py

    # Step 7: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 8: Build Docker image
    - name: Build Docker image
      run: docker build -t rbenfraj46/insurance_model:latest .

    # Step 9: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push rbenfraj46/insurance_model:latest
